title: "SIDEMIX Project"
description: "Stiffness Degradation and Micromechanical Behaviour of Sand–Fine Mixtures Under Cyclic Loading"
theme: jekyll-theme-cayman

# Optional: used for links in navigation
baseurl: "/sidemix"
url: "https://vjagodnik.github.io"
